import { Inter } from "next/font/google";
import Navbar from "./components/Navbar/Navbar";
import { Providers } from "./theme-provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar></Navbar>
          <h1>Main layout</h1>
          {children}
        </Providers>
      </body>
    </html>
  );
}
